services:
   _defaults:
      autoconfigure: true

   cgoit.monolog.additional_headers_processor:
      class: Cgoit\AdditionalHeaderLoggingBundle\Monolog\AdditionalHeadersProcessor
      arguments:
          - '@contao.framework'
